config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :quizzs do
    member do
      post :validate
    end

    resources :questions do
      resources :answers, :only => [:edit, :create, :new, :destroy, :update]
    end
  end

  resources :exams do
    member do
      resources :exam_submissions, :only => :create
    end
  end

  root 'home#index'

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :quizz
  has_many :answers

  validates_presence_of :quizz
  validates_presence_of :text

  def has_only_false_answer
    if answers.length == 0
      true
    else
      answers.each do |a|
        if a.is_correct
          return false
        end
      end
    end
    return true
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  before_action :set_quizz

  before_action :authenticate_user!

  # GET /questions
  # GET /questions.json
  def index
    @questions = @quizz.questions
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    @question.quizz = @quizz

    respond_to do |format|
      if @question.save
        format.html { redirect_to quizz_question_path(@question.quizz, @question), notice: t('question.save.success') }
        format.json { render :show, status: :created, location: quizz_question_path(@question.quizz, @question) }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to quizz_question_path(@question.quizz, @question), notice: t('question.save.success') }
        format.json { render :show, status: :ok, location: quizz_question_path(@question.quizz, @question) }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to quizz_questions_path, notice: t('question.delete.success') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:text)
    end

    def set_quizz
      @quizz = Quizz.find(params[:quizz_id])
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.haml
= form_for [@quizz,@question] do |f|
  - if @question.errors.any?
    #error_explanation
      %h2= t('question.save.error', count: @question.errors.count)
      %ul
        - @question.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :text
    = f.text_field :text, :class => 'form-control'
  .form-group
    = f.submit t('save'), :class => 'btn btn-success'

app/views/questions/edit.html.haml
.row
  .col-md-offset-4.col-md-4
    %h1=t('question.edit.title')

    = render 'form'

    = link_to =t('show'), quizz_question_path(@question.quizz, @question)
    \|
    = link_to t('back'), quizz_questions_path(@question.quizz)

app/views/questions/index.html.haml
.row
  .col-md-12
    %h1
      =t('questions.list')
      =@quizz.name
    %table.table.table-striped
      %thead
        %tr
          %th=t('questions.name')
          %th=t('actions')

      %tbody
        - @questions.each do |question|
          %tr
            %td= link_to question.text, quizz_question_path(question.quizz, question)
            %td
              = link_to edit_quizz_question_path(question.quizz, question) do
                %span.glyphicon.glyphicon-pencil
              = link_to quizz_question_path(question.quizz, question), :method => :delete, :data => { :confirm => t('delete.confirm') } do
                %span.glyphicon.glyphicon-trash

    %br

    = link_to t('question.new'), new_quizz_question_path(@quizz)

app/views/questions/new.html.haml
.row
  .col-md-offset-4.col-md-4
    %h1=t('question.new')

    = render 'form'

    = link_to t('back'), quizz_questions_path(@quizz)

app/views/questions/show.html.haml
%p#notice= notice


.row
  .col-md-12
    %h1
      =t('quizz.name')
      =@question.quizz.name

    %h2
      =t('question.name')
      =@question.text

    %p
      =t('question.answer.list')

    -if @question.has_only_false_answer
      .alert.alert-warning{:role => 'alert'}
        %strong=t('warning')
        =t('question.answer.no_correct')

    %table.table.table-striped
      %thead
        %tr
          %th=t('answer.name')
          %th=t('answer.is_correct')
          %th=t('actions')

      %tbody
        - @question.answers.each do |answer|
          %tr
            %td= answer.text
            %td= answer.is_correct
            %td
              = link_to edit_quizz_question_answer_path(answer.question.quizz, answer.question, answer) do
                %span.glyphicon.glyphicon-pencil
              = link_to quizz_question_answer_path(answer.question.quizz, answer.question, answer), :method => :delete, :data => { :confirm => 'Are you sure?' } do
                %span.glyphicon.glyphicon-trash

= link_to t('question.edit.action'), edit_quizz_question_path(@question.quizz, @question)
\|
= link_to t('question.answer.add'), new_quizz_question_answer_path(@question.quizz, @question)
\|
= link_to t('backQuizz'), quizz_path(@question.quizz)