config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :quizzs do
    member do
      post :validate
    end

    resources :questions do
      resources :answers, :only => [:edit, :create, :new, :destroy, :update]
    end
  end

  resources :exams do
    member do
      resources :exam_submissions, :only => :create
    end
  end

  root 'home#index'

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :quizz
  has_many :answers

  validates_presence_of :quizz
  validates_presence_of :text

  def has_only_false_answer
    if answers.length == 0
      true
    else
      answers.each do |a|
        if a.is_correct
          return false
        end
      end
    end
    return true
  end
end

app/models/quizz.rb
class Quizz < ActiveRecord::Base
  has_many :questions
  has_many :exams, :through => :exam_quizzs
  has_many :exam_quizzs

  validates_presence_of :intro_text
  validates_presence_of :name

end

app/controllers/quizzs_controller.rb
class QuizzsController < ApplicationController
  before_action :set_quizz, only: [:show, :edit, :update, :destroy, :validate]

  before_action :authenticate_user!, only: [:new, :edit,:update, :destroy]


  # GET /quizzs
  # GET /quizzs.json
  def index
    @quizzs = Quizz.all
  end

  # GET /quizzs/1
  # GET /quizzs/1.json
  def show
    @checked_answer_ids = []
  end

  # GET /quizzs/new
  def new
    @quizz = Quizz.new
  end

  # GET /quizzs/1/edit
  def edit
  end

  def validate
    @errors = []
    @checked_answer_ids = []

    selected_question_ids = params[:question].nil? ? [] : params[:question].keys
    selected_question_ids.each do |id|
      valid_answer_for_question = Answer.where('question_id = ? and is_correct = ?', id, true)
      selected_answers = Answer.find(params[:question][id]['answer_ids'])
      @checked_answer_ids << selected_answers.map{|a| a.id}
      unless valid_answer_for_question.uniq.sort == selected_answers.uniq.sort
        @errors << Question.find(id)
      end

    end

    quizz_question_ids = @quizz.questions.map{|q| q.id}
    quizz_question_ids.each do |id|
      unless selected_question_ids.map{|i| i.to_s}.include? id.to_s
        @errors << Question.find(id)
      end
    end

    @checked_answer_ids = @checked_answer_ids.flatten

    render :show
  end

  # POST /quizzs
  # POST /quizzs.json
  def create
    @quizz = Quizz.new(quizz_params)

    respond_to do |format|
      if @quizz.save
        format.html { redirect_to quizz_questions_path(@quizz), notice: t('quizz.save.success') }
        format.json { render :show, status: :created, location: @quizz }
      else
        format.html { render :new }
        format.json { render json: @quizz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quizzs/1
  # PATCH/PUT /quizzs/1.json
  def update
    respond_to do |format|
      if @quizz.update(quizz_params)
        format.html { redirect_to @quizz, notice: t('quizz.save.success') }
        format.json { render :show, status: :ok, location: @quizz }
      else
        format.html { render :edit }
        format.json { render json: @quizz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzs/1
  # DELETE /quizzs/1.json
  def destroy
    @quizz.destroy
    respond_to do |format|
      format.html { redirect_to quizzs_url, notice: t('quizz.delete.success') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quizz
      @quizz = Quizz.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quizz_params
      params.require(:quizz).permit(:intro_text, :name)
    end
end

app/helpers/quizzs_helper.rb
module QuizzsHelper
end

app/views/quizzs/_form.html.haml
= form_for @quizz do |f|
  - if @quizz.errors.any?
    #error_explanation
      %h2= t('quizz.save.error', count: @quizz.errors.count)
      %ul
        - @quizz.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name
    = f.text_field :name, :class => 'form-control'
  .form-group
    = f.label :intro_text
    = f.text_area :intro_text, :class => 'form-control', :rows => 5
  .form-group
    = f.submit t('save'), :class => 'btn btn-success'

app/views/quizzs/_question.html.haml
.section
  -unless @errors.nil?
    -if @errors.include? question
      .alert.alert-danger{:role => 'alert'}
        %strong=t('error')
        =t('question.answer.wrong')
  %p= question.text
  %ul.list-unstyled
    -question.answers.each do |answer|
      %li
        = radio_button_tag "question[#{question.id}]answer_ids[]", answer.id, @checked_answer_ids.include?(answer.id)
        = answer.text

app/views/quizzs/edit.html.haml
.row
  .col-md-offset-4.col-md-4
    %h1=t('quizz.edit.title')

    = render 'form'

    = link_to t('question.edit.action'), quizz_questions_path(@quizz)
    \|
    = link_to t('backQuizz'), @quizz

app/views/quizzs/index.html.haml
%h1=t('quizzs.list')
.row
  .col-md-12

    %table.table.table-striped
      %thead
        %tr
          %th= t('quizzs.name')
          - if user_signed_in?
            %th= t('actions')

      %tbody
        - @quizzs.each do |quizz|
          %tr
            %td= link_to quizz.name, quizz
            - if user_signed_in?
              %td
                = link_to edit_quizz_path(quizz) do
                  %span.glyphicon.glyphicon-pencil
                = link_to quizz, :method => :delete, :data => { :confirm => t('delete.confirm') } do
                  %span.glyphicon.glyphicon-trash

app/views/quizzs/new.html.haml
.row
  .col-md-offset-4.col-md-4
    %h1=t('quizzs.new')

    = render 'form'

app/views/quizzs/show.html.haml
%p#notice= notice

.page-header
  %h1= @quizz.name
.well
  %p= simple_format(@quizz.intro_text)

-unless @errors.nil?
  -unless @errors.any?
    .alert.alert-success{:role => 'alert'}
      %strong= t('quizz.answer.congrats.head')
      =t('quizz.answer.congrats.message')

= form_tag(validate_quizz_path(@quizz), method: :post) do
  - @quizz.questions.each do |question|
    = render 'question', :question => question
  =submit_tag(t('quizz.answer.action'), :class => 'btn btn-sm btn-success')

%br
%br
-if user_signed_in?
  = link_to t('quizz.edit.name'), edit_quizz_path(@quizz)
  \|
= link_to t('back'), quizzs_path