config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :quizzs do
    member do
      post :validate
    end

    resources :questions do
      resources :answers, :only => [:edit, :create, :new, :destroy, :update]
    end
  end

  resources :exams do
    member do
      resources :exam_submissions, :only => :create
    end
  end

  root 'home#index'

end

app/models/exam.rb
class Exam < ActiveRecord::Base
  has_many :quizzs, :through => :exam_quizzs
  has_many :exam_quizzs

  validates_presence_of :minimal_score
  validates_presence_of :name
  validates_numericality_of :minimal_score, :only_integer => true, :greater_than_or_equal_to => 0
  validates_presence_of :quizzs

  def maximal_score
    max_score = 0
    quizzs.map{|quizz| max_score += quizz.questions.count}
    max_score
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :quizz
  has_many :answers

  validates_presence_of :quizz
  validates_presence_of :text

  def has_only_false_answer
    if answers.length == 0
      true
    else
      answers.each do |a|
        if a.is_correct
          return false
        end
      end
    end
    return true
  end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_exam, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!, only: [:new, :edit,:update, :destroy]

  # GET /exams
  # GET /exams.json
  def index
    @exams = Exam.all
  end

  # GET /exams/1
  # GET /exams/1.json
  def show
    @checked_answer_ids = []
    @exam_submission = ExamSubmission.new
  end

  # GET /exams/new
  def new
    @exam = Exam.new
  end

  # GET /exams/1/edit
  def edit
  end

  # POST /exams
  # POST /exams.json
  def create
    @exam = Exam.new(exam_params)

    respond_to do |format|
      if @exam.save
        format.html { redirect_to @exam, notice: t('exam.save.success') }
        format.json { render :show, status: :created, location: @exam }
      else
        format.html { render :new }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exams/1
  # PATCH/PUT /exams/1.json
  def update
    respond_to do |format|
      if @exam.update(exam_params)
        format.html { redirect_to @exam, notice: 'Exam was successfully updated.' }
        format.json { render :show, status: :ok, location: @exam }
      else
        format.html { render :edit }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exams/1
  # DELETE /exams/1.json
  def destroy
    @exam.destroy
    respond_to do |format|
      format.html { redirect_to exams_url, notice: 'Exam was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exam_params
      params.require(:exam).permit(:minimal_score, :name, quizz_ids: [])
    end
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/exams/_form.html.haml
= form_for @exam do |f|
  - if @exam.errors.any?
    #error_explanation
      %h2= t('exam.save.error', count: @exam.errors.count)
      %ul
        - @exam.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name
    = f.text_field :name, :class => 'form-control'
  .form-group
    = f.label :minimal_score
    = f.number_field :minimal_score, :class => 'form-control'
  .form-group
    = f.label :quizzs
    = f.collection_select(:quizz_ids, Quizz.all, :id, :name, {:prompt_text => t('exam.form.select_quizzs')},{:multiple => true})
  .form-group
    = f.submit t('save'), :class => 'btn btn-success'

app/views/exams/_quizz.html.haml
.tab-pane{:role => 'tabpanel', :id => "quizz-#{quizz.id}", :class => ('active' if @exam.quizzs.first == quizz)}

  .page-header
    %h2= quizz.name
  .well
    %p= simple_format quizz.intro_text

  -unless @errors.nil?
    -unless @errors.any?
      .alert.alert-success{:role => 'alert'}
        %strong= t('quizz.answer.congrats.head')
        =t('quizz.answer.congrats.message')


  - quizz.questions.each do |question|
    .section
      -unless @errors.nil?
        -if @errors.include? question
          .alert.alert-danger{:role => 'alert'}
            %strong=t('error')
            =t('question.answer.wrong')
      %p= question.text
      %ul.list-unstyled
        -question.answers.each do |answer|
          %li
            = radio_button_tag "question[#{question.id}]answer_ids[]", answer.id, @checked_answer_ids.include?(answer.id)
            = answer.text

  - if @exam.quizzs.last == quizz
    =submit_tag t('quizz.answer.action'), :class => 'btn btn-sm btn-success'
  - else
    %a.btn.btn-sm.btn-primary.next-tab{'data-action' => 'next-tab', 'data-current-tab' => "quizz-#{quizz.id}"}
      =t('exam.quizz.next')

app/views/exams/edit.html.haml
.row
  .col-md-offset-4.col-md-4
    %h1=t('exam.edit')
    = render 'form'

app/views/exams/index.html.haml
%h1 Listing exams

%table
  %thead
    %tr
      %th Minimal score
      %th Name
      %th
      %th
      %th

  %tbody
    - @exams.each do |exam|
      %tr
        %td= exam.minimal_score
        %td= exam.name
        %td= link_to 'Show', exam
        %td= link_to 'Edit', edit_exam_path(exam)
        %td= link_to 'Destroy', exam, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Exam', new_exam_path

app/views/exams/new.html.haml
.row
  .col-md-offset-4.col-md-4
    %h1=t('exam.new')
    = render 'form'

app/views/exams/show.html.haml
.page-header
  %h1= @exam.name

=form_tag(exam_submissions_path(@exam), method: :post) do
  %div
    %ul.nav.nav-tabs{:role => 'tablist'}
      -@exam.quizzs.each do |q|
        %li{:role => 'presentation', :class => ('active' if @exam.quizzs.first == q)}
          %a{:href => "#quizz-#{q.id}", 'aria-controls' => "quizz-#{q.id}", :role => 'tab', 'data-toggle' => 'tab'}
            =q.name
    .tab-content
      -@exam.quizzs.each do |q|
        =render 'exams/quizz', :quizz => q