config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :quizzs do
    member do
      post :validate
    end

    resources :questions do
      resources :answers, :only => [:edit, :create, :new, :destroy, :update]
    end
  end

  resources :exams do
    member do
      resources :exam_submissions, :only => :create
    end
  end

  root 'home#index'

end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  %div.container
    %div.navbar-header
      %button.navbar-toggle.collapsed{'data-toggle' => 'collapse', 'data-target' => '#navbar', 'aria-expanded' => false, 'aria-controls' => 'navbar'}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      =link_to 'Quizz',root_path, :class => 'navbar-brand'
    %div#navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav
        %li.active
          =link_to t('menu.home'), root_path
        - if user_signed_in?
          %li
            =link_to t('menu.createQuizz'), new_quizz_path
          %li
            =link_to t('menu.createExam'), new_exam_path
          %li
            =link_to t('menu.logout'), destroy_user_session_path, :method => :delete
        -else
          %li
            =link_to t('menu.login'), new_user_session_path

app/views/layouts/application.html.haml
!!!5
%html{:lang => 'en'}
  %head
    %meta{:charset => 'utf-8'}
    %meta{'http-equiv' => 'X-UA-Compatible', 'content' => 'IE=edge'}
    %meta{:name => 'viewport',:content => 'width=device-width, initial-scale=1'}
    %title Quizz
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body{:role => 'document'}
    =render 'layouts/header'
    .container.theme-showcase{:role => 'main'}
      -flash.each do |name, msg|
        .alert{:class => "alert-#{name}", :role => 'alert'}
          =msg
      = yield